### ISSUE TITLE
sample tcpserver示例 listener->accept() 无法建立多个con并与client通信

### ISSUE THREAD

**Issue by shen-buding** [Hackerl/aio#3]
aio::net::stream::Listener

listener->accept() 无法建立多个con并与之通信

**Comment by Hackerl** [comment]
单次 accept 只接收一个 fd，想要接收多个可以使用 doWhile 或 loop
https://github.com/Hackerl/sSocks/blob/master/src/server.cpp#L287

**Comment by shen-buding** [comment]
![image](https://github.com/Hackerl/aio/assets/35806332/5b2b6884-c9ec-40f2-958c-06a46c30339e)
这类的双loop循环咋处理

**Comment by Hackerl** [comment]
按照这个写就行：
```cpp
    zero::async::promise::doWhile([=]() {
        return listener->accept()->then([=](const zero::ptr::RefPtr<aio::net::stream::IBuffer> &buffer) {
            // 此处不要 return，让 accpet 与读取任务并发
            zero::async::promise::doWhile([=]() {
                return buffer->read(1024)->then([=](nonstd::span<const std::byte> data) {
                    
                });
            })->fail([](const zero::async::promise::Reason &reason) {
                LOG_ERROR("code[%d] msg[%s]", reason.code, reason.message.c_str());
            });
        });
    })->fail([](const zero::async::promise::Reason &reason) {
        LOG_ERROR("code[%d] msg[%s]", reason.code, reason.message.c_str());
    })->finally([=]() {
        context->loopBreak();
    });
```
另外这个库有些设计不合理的地方之后会修复，另外我之后会基于这个框架重写一个 C++20 的协程库，毕竟 promise 写起来太耗费心智了。

**Comment by Hackerl** [comment]
使用协程就可以直接 while(true) 一直 accpet。
https://github.com/Hackerl/zero/blob/c%2B%2B20/test/async/coroutine.cpp

**Comment by shen-buding** [comment]
![image](https://github.com/Hackerl/aio/assets/35806332/79dbe43e-41f7-45c2-a986-8c56f4776b27)
我后面改成这样是可以的, 我到时候跟进你的20版本
